import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Constructor } from '../components/constructor';
import { useState } from 'react'

export default function Home() {
  const [scripts, setScripts] = useState([{ id: 1, isAsync: false, isDefer: false, delay: 1}]);

  function handleAddItemClick(){
    const maxId = Math.max(...scripts.map(x => x.id));
    const newScript = { id: maxId + 1, isAsync: false, isDefer: false, delay: 0 };
    setScripts([...scripts, newScript]);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Constructor scripts={scripts} addItem={handleAddItemClick}></Constructor>
      </main>
    </>
  )
}
